Repository paquesid/paques-website-automation, pull requests merged in 2022-07, with the labels that each got.

#32 add scenario run query command using search file
  .github/package.yml
  src/test/java/elements/DataProcessingElement.java
  src/test/java/helper/TestInstrument.java
  src/test/java/pages/DataProcessingPage.java
  src/test/java/stepdefinitions/QuerySteps.java
  src/test/resources/features/DataProcessing/TC02_RunQueryCommand.feature
Labels: BDD Cucumber, Automation

#35 implement telegram bot
  .github/workflow/package.yml
  .github/workflow/telegram.yml
  env/env.sample
  pom.xml
  src/test/java/helper/Constant.java
  src/test/java/stepdefinitions/TelegramBot.java
  src/test/java/telegram/TelegramStep.java
  src/test/resources/features/telegram/dailyStandUp.feature
Labels: enhancement

#36 fixing typo workflows
  .github/workflows/package.yml
  .github/workflows/telegram.yml
Labels: bug

#37 fix github action deploy package
  .github/workflows/package.yml
  pom.xml
Labels: bug

#38 adjust logic test instrument
  src/test/java/helper/CucumberPages.java
  src/test/java/helper/TestInstrument.java
Labels: BDD Cucumber, Automation

#39 implement scenario edit metadata
  src/test/java/elements/DataProcessingElement.java
  src/test/java/pages/DataProcessingPage.java
  src/test/java/stepdefinitions/EditMetaDataStep.java
  src/test/resources/features/DataProcessing/TC04_EditMetaData.feature
Labels: BDD Cucumber, Automation

#43 add element scheduller
  .github/workflows/package.yml
  .github/workflows/telegram.yml
  pom.xml
  src/test/java/elements/DataProcessingElement.java
  src/test/java/helper/CucumberPages.java
  src/test/java/helper/Environment.java
  src/test/java/stepdefinitions/TelegramBot.java
  src/test/java/telegram/TelegramStep.java
  src/test/java/testRunner/RunCucumberTest.java
  src/test/java/utils/LogUtils.java
  src/test/resources/features/telegram/dailyStandUp.feature
Labels: BDD Cucumber, Automation

#44 Adjust TC Edit Metadata
  env/env.sample
  pom.xml
  src/test/java/elements/DataProcessingElement.java
  src/test/java/helper/Base.java
  src/test/java/helper/TestInstrument.java
  src/test/java/pages/DataProcessingPage.java
  src/test/java/pages/ForgotPasswordPage.java
  src/test/java/pages/UsersPage.java
  src/test/resources/features/DataProcessing/TC03_EditMetaData.feature
  src/test/resources/features/DataProcessing/TC04_EditMetaData.feature
Labels: BDD Cucumber, Automation

#42 edit group
  .github/workflows/action.yml
  env/env.sample
  src/test/java/elements/GroupPageElement.java
  src/test/java/elements/RoleElement.java
  src/test/java/helper/Base.java
  src/test/java/helper/CucumberPages.java
  src/test/java/helper/Type.java
  src/test/java/pages/CreateRolePage.java
  src/test/java/pages/GroupPage.java
  src/test/java/pages/HomePage.java
  src/test/java/stepdefinitions/CreateRoleSteps.java
  src/test/java/stepdefinitions/GroupSteps.java
  src/test/resources/features/CreateRole.feature
  src/test/resources/features/CreateUser.feature
  src/test/resources/features/EditRole.feature
  src/test/resources/features/ForgotPassword.feature
  src/test/resources/features/Login.feature
  src/test/resources/features/UserManagement/Group/CreateGroup.feature
  src/test/resources/features/UserManagement/Group/EditGroup.feature
  src/test/resources/features/UserManagement/Role/CreateRole.feature
  src/test/resources/features/UserManagement/Role/DeleteRole.feature
  src/test/resources/features/UserManagement/Role/EditRole.feature
  src/test/resources/features/UserManagement/Roles/CreateRole.feature
  src/test/resources/features/UserManagement/Users/TC02_UpdateUser.feature
Labels: BDD Cucumber, Automation

#46 add docs steps installation jenkins
  docs/installation-jenkins.md
Labels: documentation

#47 remove scenario test in root folder
  .github/workflows/action.yml
  src/test/resources/features/CreateRole.feature
  src/test/resources/features/CreateUser.feature
  src/test/resources/features/EditRole.feature
  src/test/resources/features/ForgotPassword.feature
  src/test/resources/features/Login.feature
Labels: bug

#48 fixing whitespace & adjust time to milliseconds
  env/env.sample
  pom.xml
  src/test/java/config/Hooks.java
  src/test/java/elements/RoleElement.java
  src/test/java/helper/Constant.java
  src/test/java/helper/Environment.java
  src/test/java/helper/TestInstrument.java
  src/test/java/pages/CreateRolePage.java
  src/test/java/pages/GroupPage.java
  src/test/java/pages/HomePage.java
  src/test/java/pages/LoginPage.java
  src/test/java/pages/UsersPage.java
  src/test/java/stepdefinitions/CreateRoleSteps.java
  src/test/java/stepdefinitions/GroupSteps.java
  src/test/java/stepdefinitions/UsersSteps.java
  src/test/java/testRunner/RunCucumberTest.java
Labels: enhancement
